### ISSUE TITLE
Visual Studio Issue

### ISSUE THREAD

**Issue by PaytonCasey** [RootKiller/MSCMP#1]
Can't compile a project because get this error : 
"1>CSC : error CS2001: Could not find the source file "C:\Steam\steamapps\common\My Summer Car\MSCMP-master\src\MSCMPClient\Network\NetMessages.generated.cs"."

I tried to compile by parts and nothing.

**Comment by RootKiller** [comment]
Follow the instructions in https://github.com/RootKiller/MSCMP/blob/master/readme.md

**Comment by Vikanen** [comment]
In the readme there stays "First of all compile and run MSCMPMessages app". Excuse me, but how do i compile and run it? I tried building it but now i'm pretty sure i should not do that.
